// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"shrumjuvhl","name":"RatedItemsCRUD","description":"","endpoint":"https://shrumjuvhl.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/RatedItems","/RatedItems/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:882eee02-760c-4b4b-a05a-a4f8135924b0',
    'aws_cognito_region': 'us-east-1',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"fooddeliveryapp-mobilehub-211733734-RatedItems","attributes":[{"name":"userId","type":"S"},{"name":"itemId","type":"S"},{"name":"category","type":"S"},{"name":"details","type":"S"},{"name":"name","type":"S"},{"name":"ratingCount","type":"N"},{"name":"ratingValue","type":"N"}],"indexes":[{"indexName":"Ratings","hashKey":"category","rangeKey":"ratingValue"}],"region":"us-east-1","hashKey":"userId","rangeKey":"itemId"}],
    'aws_mobile_analytics_app_id': '481e089dafcb4becb4b5beeef82a4a00',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '495f55c6-619d-4666-afdf-9c6c2ff40960',
    'aws_project_name': 'FoodDeliveryApp',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'fooddeliveryapp-deployments-mobilehub-211733734',
    'aws_resource_name_prefix': 'fooddeliveryapp-mobilehub-211733734',
}

export default awsmobile;
