// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"af2rfbtfg3","name":"sampleCloudApi","description":"","endpoint":"https://af2rfbtfg3.execute-api.us-east-2.amazonaws.com/Development","region":"us-east-2","paths":["/items","/items/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-2:b3752037-2689-4187-99cb-660b066a8694',
    'aws_cognito_region': 'us-east-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'fooddelivery-hosting-mobilehub-24154540',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd18vux1sg60itr.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-2',
    'aws_dynamodb_table_schemas': [{"tableName":"fooddelivery-mobilehub-24154540-TestLocation","attributes":[{"name":"userId","type":"S"},{"name":"itemId","type":"S"},{"name":"category","type":"S"},{"name":"image","type":"S"},{"name":"latitude","type":"N"},{"name":"longitude","type":"N"},{"name":"name","type":"S"},{"name":"something1","type":"S"},{"name":"something2","type":"S"},{"name":"spicy","type":"S"}],"indexes":[{"indexName":"Categories","hashKey":"category","rangeKey":"longitude"}],"region":"us-east-2","hashKey":"userId","rangeKey":"itemId"},{"tableName":"fooddelivery-mobilehub-24154540-AWSMobileTable","attributes":[{"name":"teamId","type":"S"},{"name":"personId","type":"S"},{"name":"email","type":"S"},{"name":"personName","type":"S"},{"name":"phone","type":"S"}],"indexes":[{"indexName":"personName-index","hashKey":"teamId","rangeKey":"personName"}],"region":"us-east-2","hashKey":"teamId","rangeKey":"personId"}],
    'aws_mobile_analytics_app_id': '3bdd78fb08a74996a0278ad5c42ff061',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '85fd66ef-b940-4733-9257-0682b05adb58',
    'aws_project_name': 'FoodDelivery',
    'aws_project_region': 'us-east-2',
    'aws_resource_bucket_name': 'fooddelivery-deployments-mobilehub-24154540',
    'aws_resource_name_prefix': 'fooddelivery-mobilehub-24154540',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'fooddelivery-userfiles-mobilehub-24154540',
    'aws_user_files_s3_bucket_region': 'us-east-2',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-2_d8zc5DMvI',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '21gp6gei76bsqjpl396cc17tmu',
}

export default awsmobile;
